services:
  # Backend FastAPI Service
  - type: web
    name: homewiz-chat-backend
    runtime: docker
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME # Change this
    region: ohio # e.g., ohio, oregon
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: EMAIL_HOST
        fromSecret: EMAIL_HOST
      - key: EMAIL_PORT
        fromSecret: EMAIL_PORT
      - key: EMAIL_USER
        fromSecret: EMAIL_USER
      - key: EMAIL_PASSWORD
        fromSecret: EMAIL_PASSWORD
    # Free tier instances spin down. A persistent disk ensures the
    # SQLite DB file is not lost.
    disk:
      name: sqlite-data
      mountPath: /code
      sizeGB: 1

  # Frontend React Static Site
  - type: web
    name: homewiz-chat-frontend
    runtime: static
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME # Change this
    region: ohio
    plan: free
    staticPublishPath: ./frontend/dist
    buildCommand: |
      cd frontend &&
      npm install &&
      npm run build
    # Add a rewrite rule for single-page applications
    routes:
      - type: rewrite
        source: /*
        destination: /index.html